// Both pages have static copy. This supplements runtime hero/motion messages
// and preserves legacy sample translations. No automatic language redirect.
export const translations = {
 "25 minutes of focus with Mino.":"Mino ile 25 dakika odaklanma.",
 "Session complete. A leaf for your bowl.":"Seans tamamlandı. Kasene bir yaprak eklendi.",
 "Focused time becomes a lasting trace.":"Odaklandığın zaman kalıcı bir iz bırakır.",
 "Choose a detail for your room.":"Odan için bir detay seç.",
 "Your room becomes a little more yours.":"Odan sana biraz daha ait olur.",
 "2 focused hours. Your Reading chapter grows.":"2 saat odaklanma. Okuma bölümün gelişiyor.",
 "6 focused hours. Another layer takes shape.":"6 saat odaklanma. Yeni bir katman oluşuyor.",
 "15 focused hours. Your chapter grows richer.":"15 saat odaklanma. Bölümün yeni izler taşıyor.",
 "A chapter finished. A memory kept.":"Bölüm tamamlandı. Hatırası odanda kaldı.",
 "A completed chapter, kept. Reduced-motion preview.":"Tamamlanan bölüm saklandı. Sabit önizleme.",
 "Accelerated preview":"Hızlandırılmış gösterim",
 "Website sample reset. Your real app history is never changed.":"Web sitesi örneği sıfırlandı. Gerçek uygulama geçmişin değişmez.",
 "First sample chapter finished. The memory box has joined the room.":"İlk örnek bölüm tamamlandı. Hatıra kutusu odadaki yerini aldı.",
 "Mino focusing with a notebook":"Mino bir defterle odaklanıyor", "Mino resting with eyes closed":"Mino gözleri kapalı dinleniyor", "Mino welcoming you back with a wave":"Mino el sallayarak seni karşılıyor",
 "a fuller chapter":"daha dolu bir bölüm", "a second layer":"ikinci bir katman", "a new material":"yeni bir malzeme",
 "A finished chapter, kept.":"Tamamlanan bölüm saklandı.",
 "One session. A trace in your room.":"Bir seans, odanda bir iz.", "Illustrative time-lapse":"Temsili zaman atlaması", "Example complete":"Örnek tamamlandı", "Example paused":"Örnek duraklatıldı", "Resume":"Devam et", "Resume animated example":"Örneğe devam et", "Static preview. Enable JavaScript to watch the example.":"Sabit önizleme. Örneği izlemek için JavaScript’i aç.",
 "Replay chapter time-lapse":"Bölüm örneğini yeniden oynat",
 "35 credited sessions. A full bowl earns the ceramic leaf; the bowl stays full.":"35 geçerli seans. Dolu kase seramik yaprağı kazandırır; kase dolu kalır.", "Reading chapter preview, first shape":"Okuma bölümü, ilk biçim",
 "first shape":"ilk biçim", "A calm focus timer for iPhone. Focus with Mino, keep a personal chapter, and choose decor with earned Star Dust.":"iPhone için sakin bir Pomodoro zamanlayıcısı. Mino ile odaklan, kişisel bölümler biriktir ve kazanılan Yıldız Tozu ile dekor seç.", "Focus with Mino. Keep your story. Make a room your own.":"Mino ile odaklan. Hikâyeni biriktir. Odanı kendine ait kıl.",
 "Focus Habitat home":"Focus Habitat ana sayfa", "Reading chapter, first shape":"Okuma bölümü, ilk biçim", "One walnut arch with a cream paper layer":"Kâğıt katmanıyla bir ceviz kemer", "Two nested walnut arches with cream layers":"Kâğıt katmanlarıyla iki iç içe ceviz kemer", "Three nested arches with a moss fabric layer":"Yosun renkli kumaşla üç iç içe kemer", "Four nested walnut, paper and moss arches":"Ceviz, kâğıt ve kumaşla dört iç içe kemer", "The app's walnut memory box":"Uygulamanın ceviz hatıra kutusu", "Wooden sprout medal":"Ahşap filiz madalyası", "Wooden sun medal":"Ahşap güneş madalyası", "Wooden mountain medal":"Ahşap dağ madalyası", "Leaf bowl preview":"Yaprak kasesi önizlemesi", "Ceramic bowl with one earned leaf":"Kazanılan bir yaprakla seramik kase", "A ceramic leaf, earned when the bowl is full":"Kase dolduğunda kazanılan seramik yaprak", "Mino sitting quietly on a moss cushion":"Yosun renkli minderde sessizce oturan Mino", "Actual Focus Habitat app during a 25-minute focus, with the furnished room and Mino":"Gerçek Focus Habitat uygulamasında Mino ile 25 dakikalık odaklanma", "Actual session complete screen: a leaf for the bowl and 2 Star Dust":"Gerçek tamamlanma ekranı: kaseye bir yaprak ve 2 Yıldız Tozu", "Actual Journey screen showing the Reading chapter and its focused time":"Okuma bölümünü ve odaklanma süresini gösteren gerçek Yolculuk ekranı", "Actual You screen with this week's time together and Mino":"Bu haftaki zamanı ve Mino’yu gösteren gerçek Sen ekranı", "Actual room screen, ready to start a 25-minute focus":"25 dakikalık seansa hazır gerçek oda ekranı",
 "Focus Habitat | A little time. Something yours.":"Focus Habitat | Biraz zaman. Sana ait.",
 "Focus Habitat — Pomodoro & Focus Timer for iPhone":"Focus Habitat — iPhone için Pomodoro ve Odaklanma Zamanlayıcısı",
 "Skip to content":"İçeriğe geç", "The collection":"Koleksiyon", "Your story":"Hikâyen", "Support":"Destek",
 "Coming soon to the App Store":"App Store’da yakında", "Reading Lamp":"Okuma Lambası", "Small Fern":"Küçük Eğrelti", "See it grow":"Gelişimini izle",
 "A calm focus timer for iPhone":"iPhone için sakin bir odaklanma zamanlayıcısı", "A calm Pomodoro-style timer for iPhone":"iPhone için odaklanma ve Pomodoro zamanlayıcısı",
 "A little time.":"Biraz zaman.", "Something":"Sana", "yours.":"ait.", "Focus with Mino. Keep your story.":"Mino ile odaklan. Hikâyeni biriktir.", "Make a room your own.":"Odanı kendine ait kıl.", "Try it yourself":"Kendin dene",
 "Animated example":"Hızlandırılmış örnek", "A little focus with Mino.":"Mino ile biraz odaklan.", "Focus":"Odaklan", "Keep":"Biriktir", "Choose":"Seç", "Grow":"Geliştir", "Pause":"Duraklat", "Play":"Oynat", "Replay":"Yeniden oynat",
 "A little focus.":"Biraz odaklan.", "A little something for your room.":"Odan için küçük bir şey.", "Try your own sample completion, then choose where your earned Star Dust goes.":"Örnek bir seansı tamamla, ardından kazandığın Yıldız Tozu ile dekorunu seç.",
 "A leaf for the bowl":"Kaseye bir yaprak", "Earned Star Dust":"Kazanılan Yıldız Tozu", "Decor that stays":"Kalıcı dekor", "Website demo. Sample history only.":"Web sitesi demosu. Yalnızca örnek geçmiş.", "Star Dust":"Yıldız Tozu",
 "Complete sample focus":"Örnek seansı tamamla", "Reset sample":"Örneği sıfırla", "Choose a decor object":"Bir dekor seç", "Place Small Fern":"Eğreltiyi yerleştir", "Place Reading Lamp":"Lambayı yerleştir",
 "Start with 4 saved Dust. An eligible 25-minute completion adds 2.":"4 Yıldız Tozu ile başla. Uygun bir 25 dakikalık seans 2 toz ekler.",
 "Dust is earned on eligible completions, with a daily limit. It is never sold for money.":"Toz, günlük sınırla uygun seanslardan kazanılır. Para ile satılmaz.",
 "This room is a static preview. Enable JavaScript to try the sample interactions.":"Bu oda sabit bir önizleme. Örnek etkileşimler için JavaScript’i aç.",
 "Return to a chapter.":"Bir bölüme geri dön.", "Watch it take shape.":"Şekillenmesini izle.", "Optional labels connect your focus to a story.":"İsteğe bağlı etiketler, odaklandığın zamanı bir hikâyeye bağlar.", "Reading":"Okuma", "Illustrative time-lapse":"Temsili zaman atlaması", "First shape":"İlk biçim", "A second layer":"İkinci bir katman", "A new material":"Yeni bir malzeme", "A fuller chapter":"Daha dolu bir bölüm",
 "At least 3 completed sessions and 45 focused minutes.":"En az 3 tamamlanan seans ve 45 dakika odaklanma.", "Watch the chapter grow":"Bölümün gelişimini izle", "Finish sample chapter":"Örnek bölümü tamamla", "Finish a chapter when it feels complete. Its history stays.":"Tamamlandığını hissettiğinde bölümü bitir. Geçmişi kalır.", "A finished chapter, kept.":"Tamamlanan bölüm, saklandı.", "The memory box has joined your room.":"Hatıra kutusu odana katıldı.",
 "Keepsakes":"Hatıralar", "Time leaves":"Zamanın", "something real.":"gerçek bir iz bırakır.", "Small traces of the time you gave yourself.":"Kendine ayırdığın zamanın küçük izleri.", "A leaf for every":"Her geçerli seans", "credited session.":"için bir yaprak.", "Your bowl fills, then stays full.":"Kasen dolar ve dolu kalır.", "Nothing you earn is taken away.":"Kazandıkların elinden alınmaz.", "First leaf":"İlk yaprak", "A full bowl":"Dolu bir kase", "One credited session, one leaf.":"Bir geçerli seans, bir yaprak.",
 "Rest":"Dinlen", "Welcome back":"Hoş geldin", "Quiet company":"Odaklanırken", "for your focus.":"sakin bir eşlik.", "Mino works alongside you, rests with you, and welcomes you back.":"Mino seninle çalışır, dinlenir ve dönüşünü karşılar.", "No feeding.":"Beslemek yok.", "No care chores.":"Bakım işleri yok.", "No guilt.":"Suçluluk yok.",
 "On iPhone":"iPhone’da", "Made to fit your day.":"Gününe uyum sağlar.", "Start on iPhone. Stay with your focus.":"iPhone’da başla. Odağında kal.", "The real app.":"Gerçek uygulama.", "During focus, Mino works alongside you.":"Odaklanırken Mino seninle çalışır.", "Complete":"Tamamla", "Journey":"Yolculuk", "You":"Sen", "Room":"Oda", "Live Activities":"Canlı Etkinlikler", "A glance at your remaining time.":"Kalan süreni bir bakışta gör.", "Home Screen widget":"Ana Ekran widget’ı", "A quieter way back in.":"Geri dönmenin sakin bir yolu.", "Siri shortcuts":"Siri kestirmeleri", "Start with your voice.":"Sesinle başla.", "Clear, spoken controls.":"Anlaşılır, sesli kontroller.", "Reduce Motion":"Hareketi Azalt", "A still, comfortable experience.":"Sakin ve rahat bir deneyim.", "iPhone with iOS 17 or later. 12 languages.":"iOS 17 ve üzeri iPhone. 12 dil.",
 "A little more":"Biraz daha", "atmosphere.":"atmosfer.", "Habitat Plus is optional.":"Habitat Plus isteğe bağlıdır.", "11 offline soundscapes":"Çevrimdışı 11 ortam sesi", "Decor colour finishes and the amber star":"Dekor renkleri ve kehribar yıldız", "A monthly leaf calendar":"Aylık yaprak takvimi", "Four keepsake sharing papers":"Hatıralar için dört paylaşım kâğıdı", "Focus, personal history and earned progress stay free.":"Odaklanma, kişisel geçmiş ve kazanılan ilerleme ücretsiz kalır.", "About membership":"Üyelik hakkında",
 "Privacy":"Gizlilik", "Your time":"Zamanın", "belongs to you.":"sana ait.", "No account. No server.":"Hesap yok. Sunucu yok.", "Your focus history stays on your iPhone.":"Odaklanma geçmişin iPhone’unda kalır.", "Read the privacy policy":"Gizlilik politikasını oku", "A few things you may wonder":"Merak edebileceklerin", "Do I need an account?":"Hesap gerekiyor mu?", "No. Open the app and begin.":"Hayır. Uygulamayı aç ve başla.", "What does Star Dust buy?":"Yıldız Tozu ile ne alırım?", "Permanent decor for your room. Dust is earned on eligible completions with a daily limit, and is never sold for money.":"Odan için kalıcı dekor. Toz, günlük sınırla uygun seanslardan kazanılır; para ile satılmaz.", "Can I focus without a label?":"Etiket olmadan odaklanabilir miyim?", "Yes. Labels are optional. Your credited time, leaves and keepsakes still count.":"Evet. Etiketler isteğe bağlıdır. Geçerli süren, yaprakların ve hatıraların yine birikir.", "Is Habitat Plus required?":"Habitat Plus gerekiyor mu?", "No. Focus, personal history and everything you earn stay free.":"Hayır. Odaklanma, kişisel geçmiş ve kazandığın her şey ücretsiz kalır.",
 "Make room for":"Biraz odaklanmaya", "a little focus.":"yer aç.", "Focus Habitat for iPhone.":"iPhone için Focus Habitat.", "Get support":"Destek al", "A small sample room":"Küçük bir örnek oda", "Close":"Kapat", "Watch room take shape":"Odanın gelişimini izle", "Illustrative room time-lapse":"Temsili oda zaman atlaması", "Terms of Use":"Kullanım Koşulları",
 "Can I use it for Pomodoro-style focus?":"Focus Habitat ile Pomodoro yapabilir miyim?", "Yes. Choose a 25-minute session or a length that suits you. Take a break when you need one, then begin again.":"Evet. 25 dakikalık bir seans ya da sana uygun bir süre seç. İhtiyaç duyduğunda mola ver, sonra yeniden başla.",
 "25 quiet minutes with Mino.":"Mino ile 25 sakin dakika.", "Focus complete. One leaf, kept.":"Seans tamamlandı. Bir yaprak saklandı.", "2 earned Dust. Your balance is 6.":"2 Toz kazandın. Bakiyen 6.", "A Small Fern, chosen for 6 Dust.":"6 Toz ile küçük bir eğrelti seçildi.", "Your fern settles into the room.":"Eğreltin odadaki yerini aldı.", "2 hours. A second Reading layer.":"2 saat. Okuma bölümünde ikinci katman.", "6 hours. A new material appears.":"6 saat. Yeni bir malzeme oluştu.", "15 hours. A fuller chapter and bowl.":"15 saat. Daha dolu bir bölüm ve kase.", "A finished chapter, kept in your room.":"Tamamlanan bölüm odanda saklandı.", "Your turn. Choose how the room grows.":"Sıra sende. Odanın nasıl gelişeceğini seç.", "A focused chapter, kept. Motion reduced.":"Odaklandığın bölüm saklandı. Hareket azaltıldı.", "Still preview":"Sabit önizleme", "Static example with reduced motion":"Hareketi azaltılmış sabit örnek",
 "Pause animated example":"Örneği duraklat", "Play animated example":"Örneği oynat", "Replay animated example":"Örneği yeniden oynat", "Open menu":"Menüyü aç", "Close menu":"Menüyü kapat", "Close room demo":"Örnek odayı kapat", "Pause screen slideshow":"Ekran geçişini duraklat", "Play screen slideshow":"Ekran geçişini oynat", "Pause all motion":"Tüm hareketi durdur", "Resume motion":"Hareketi aç", "Main navigation":"Ana gezinme", "Language":"Dil", "Legal":"Yasal bağlantılar", "Example stages":"Örnek aşamalar", "How the sample works":"Örnek nasıl çalışır", "Inspect Reading chapter forms":"Okuma bölümünün biçimleri", "Mino poses":"Mino’nun duruşları", "App screens":"Uygulama ekranları", "Example Star Dust":"Örnek Yıldız Tozu",
 "Sample chapter finished":"Örnek bölüm tamamlandı", "Small Fern placed":"Eğrelti yerleştirildi", "Reading Lamp placed":"Lamba yerleştirildi", "Chapter kept":"Bölüm saklandı", "Room sample finished":"Oda örneği tamamlandı", "Pause room time-lapse":"Oda örneğini duraklat", "Replay room time-lapse":"Oda örneğini yeniden oynat", "Resume room time-lapse":"Oda örneğine devam et", "Resume chapter time-lapse":"Bölüm örneğine devam et", "Pause chapter time-lapse":"Bölüm örneğini duraklat",
 "25 focused minutes kept. One leaf and 2 Star Dust earned.":"25 dakika saklandı. Bir yaprak ve 2 Yıldız Tozu kazandın.", "25 focused minutes and one leaf kept. Today’s sample Dust limit is reached.":"25 dakika ve bir yaprak saklandı. Bugünün örnek Toz sınırına ulaşıldı.", "An accelerated chapter example is playing. Pause or inspect any form.":"Hızlandırılmış bölüm örneği oynuyor. Duraklat ya da bir biçimi incele.", "Time-lapse shown as its final state because Reduce Motion is on. Inspect each form above.":"Hareketi Azalt açık olduğu için son durum gösteriliyor. Yukarıdan biçimleri inceleyebilirsin.", "You are inspecting a form. Previously earned sample history stays; the stage selector does not erase it.":"Bir biçimi inceliyorsun. Kazanılan örnek geçmiş korunur; biçim seçimi onu silmez.", "A second layer joins your Reading chapter.":"Okuma bölümüne ikinci bir katman katılır.", "More focused time brings a new material and another layer.":"Daha fazla odaklanma, yeni bir malzeme ve katman getirir.", "Four layers hold the time you have given this chapter.":"Dört katman bu bölüme ayırdığın zamanı taşır.", "Your sample chapter is finished.":"Örnek bölümün tamamlandı.",
 "Complete a session. A leaf for the bowl.":"Seansı tamamla. Kaseye bir yaprak.", "Journey keeps every chapter you return to.":"Yolculuk, döndüğün her bölümü saklar.", "A quiet look at your week together.":"Birlikte geçirdiğiniz haftaya sakin bir bakış.", "Your room, ready when you are.":"Sen hazır olduğunda odan da hazır.",
 "6 Star Dust · permanent decor":"6 Yıldız Tozu · kalıcı dekor", "3 leaves kept":"3 yaprak saklandı", "75 min in Reading":"Okuma için 75 dk", "1 h 15 min":"1 sa 15 dk", "3 sessions":"3 seans", "3 sessions + 45 min":"3 seans + 45 dk", "2 hours":"2 saat", "6 hours":"6 saat", "15 hours":"15 saat"
};

export function translate(value) {
 if (typeof value !== 'string') return value;
 const key=value.trim();
 if(translations[key]) return value.replace(key,translations[key]);
 const history=key.match(/^Sample Reading history: (\d+) completed sessions, (\d+) focused minutes\. Time is accelerated here\.$/);
 if(history)return value.replace(key,`Örnek Okuma geçmişi: ${history[1]} tamamlanan seans, ${history[2]} dakika odaklanma. Burada zaman hızlandırıldı.`);
 const chapter=key.match(/^Reading chapter (?:example, form|preview,) (.+)$/);
 if(chapter)return value.replace(key,`Okuma bölümü, ${translations[chapter[1]] || chapter[1]}`);
 const cost=key.match(/^(Reading Lamp|Small Fern) costs 6 Dust\. (Complete eligible sample focus to reach 6\.|You can place it now\.)$/);
 if(cost)return value.replace(key,`${translations[cost[1]]} 6 Yıldız Tozu tutar. ${cost[2].startsWith('Complete')?'6 toza ulaşmak için uygun örnek seansı tamamla.':'Şimdi yerleştirebilirsin.'}`);
 const owned=key.match(/^(Reading Lamp|Small Fern) is already in your room\.$/);
 if(owned)return value.replace(key,`${translations[owned[1]]} zaten odanda.`);
 const rules=[[/^(\d+) leaves kept$/, '$1 yaprak saklandı'],[/^(\d+) min in Reading$/, 'Okuma için $1 dk'],[/^(\d+) sessions?$/, '$1 seans'],[/^(\d+) h(?: (\d+) min)?$/, (_,h,m)=>`${h} sa${m?' '+m+' dk':''}`],[/^(\d+) min$/, '$1 dk'],[/^(\d+) Reading minutes, (\d+) leaves kept\. Time accelerated\.$/,'$1 dakika Okuma, $2 yaprak saklandı. Zaman hızlandırıldı.'],[/^Your chapter keeps its earned form (\d)\. Finishing it does not add unearned layers\.$/,'Bölümün kazandığı $1. biçimi korunur. Bitirmek kazanılmamış katman eklemez.'],[/^Reading chapter (?:example, form|preview,) (.+)$/,'Okuma bölümü, $1']];
 rules.push([/^(\d+) hours$/,'$1 saat'],[/^(Reading Lamp|Small Fern) costs 6 earned Star Dust\.$/,(_,name)=>`${translations[name]} 6 Yıldız Tozu tutar.`],[/^(Reading Lamp|Small Fern),? chosen with 6 earned Star Dust\. It stays in your room\.$/,(_,name)=>`${translations[name]} 6 Yıldız Tozu ile seçildi. Odanda kalır.`],[/^Ceramic bowl with (\d+) earned (?:leaf|leaves)$/,'Kazanılan $1 yaprakla seramik kase']);
 for(const [pattern,replacement]of rules)if(pattern.test(key))return value.replace(key,key.replace(pattern,replacement));
 let result=value;
 for(const source of ['First shape','2 hours','6 hours','15 hours'])if(result.trimStart().startsWith(source+'. '))result=result.replace(source,translations[source]);
 // Composite runtime messages join fixed, already-translated sentence fragments.
 for(const source of Object.keys(translations).sort((a,b)=>b.length-a.length)) {
   if(source.length>18 && result.includes(source)) result=result.replaceAll(source,translations[source]);
 }
 return result;
}

export function initLanguage() {
 if(document.documentElement.lang!=='tr')return;
 const visit=node=>{
   if(node.nodeType===3 && !['SCRIPT','STYLE'].includes(node.parentElement?.tagName)) { const text=translate(node.data);if(text!==node.data)node.data=text; }
   else if(node.nodeType===1){
     for(const name of ['aria-label','alt','data-caption'])if(node.hasAttribute(name)){const old=node.getAttribute(name),next=translate(old);if(old!==next)node.setAttribute(name,next);}
     for(const child of node.childNodes)visit(child);
   }
 };
 visit(document.body);
 new MutationObserver(records=>{
   for(const record of records){if(record.type==='childList')record.addedNodes.forEach(visit);else visit(record.target);}
 }).observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','alt','data-caption']});
}
